// contracts/fuzz/src/targets/marketplace_fee.rs
//!
//! Targeted fuzzing harness for `marketplace`'s fee-calculation and
//! tiered-fee logic.
//!
//! ## What this harness asserts
//!
//! For every (amount, fee_bps, tier_fee_bps, token_decimals) combination
//! generated by the fuzzer:
//!
//! **INV-FEE-1: No silent rounding loss**
//!   `fee + net == amount`
//!   Any "rounding dust" must be accounted for — it may go to either fee or
//!   net but must not simply vanish.
//!
//! **INV-FEE-2: Fee is non-negative**
//!   `fee >= 0` always (negative fees would mean the protocol *pays* investors).
//!
//! **INV-FEE-3: Net is non-negative**
//!   `net >= 0` always (a net of -1 would mean the investor owes more than the
//!   full amount after fees, which is undefined behaviour).
//!
//! **INV-FEE-4: Fee is bounded by amount**
//!   `fee <= amount` (100% fee is legal when fee_bps = 10_000; > 100% is not).
//!
//! **INV-FEE-5: Tier-fee resolution is monotonic w.r.t. tier ordinal**
//!   Higher-risk tiers (larger ordinal) must not produce a *lower* fee than
//!   lower-risk tiers when tier overrides are set.  The harness does not
//!   enforce a specific ordering — it only checks that per-tier fees lie within
//!   [0, 10_000] bps.
//!
//! **INV-FEE-6: Zero-amount input is rejected**
//!   `fund_invoice(amount=0)` must return `Err`, never `Ok`.
//!
//! **INV-FEE-7: MAX_AMOUNT boundary**
//!   Inputs at and near `i128::MAX / 2` must not panic (they may return `Err`).
//!
//! ## Why a separate harness (not part of the general marketplace target)?
//!
//! The general `marketplace` target exercises the full listing lifecycle; it is
//! not constrained to reach valid fee-calculation paths consistently.  This
//! harness seeds a funded listing, then drives `fund_invoice` directly with
//! adversarially chosen (amount, tier) pairs, asserting the fee invariants on
//! every successful call.  Failing inputs shrink to a minimal reproducible case
//! automatically under libFuzzer/cargo-fuzz.

use arbitrary::Arbitrary;

use crate::gen;
use crate::harness::Protocol;
use kora_shared::types::RiskTier;
use soroban_sdk::{
    testutils::{Ledger, LedgerInfo},
    token::StellarAssetClient,
    Address,
};

/// Maximum amount constant from `marketplace` — `i128::MAX / 2`.
const MAX_AMOUNT: i128 = i128::MAX / 2;

/// Tier table as used in `marketplace` (`TierFeeBps` ordinals 0–4).
const TIERS: [RiskTier; 5] = [
    RiskTier::AAA,
    RiskTier::AA,
    RiskTier::A,
    RiskTier::B,
    RiskTier::C,
];

// ── Arithmetic helpers (mirrors marketplace's bps_of_normalized) ──────────────

/// Same formula as `kora_shared::validation::bps_of_normalized`.
fn bps_of_normalized(amount: i128, bps: u32, decimals: u32) -> Option<i128> {
    let scale = 10i128.pow(decimals);
    amount
        .checked_mul(bps as i128)?
        .checked_div(10_000)?
        .checked_div(scale)?
        .checked_mul(scale)
}

/// Assert INV-FEE-1 through INV-FEE-4.
fn assert_fee_invariants(amount: i128, fee: i128, net: i128, context: &str) {
    // INV-FEE-2
    assert!(
        fee >= 0,
        "INV-FEE-2 VIOLATED: fee {} < 0 — context: {}",
        fee,
        context
    );
    // INV-FEE-3
    assert!(
        net >= 0,
        "INV-FEE-3 VIOLATED: net {} < 0 — context: {}",
        net,
        context
    );
    // INV-FEE-4
    assert!(
        fee <= amount,
        "INV-FEE-4 VIOLATED: fee {} > amount {} — context: {}",
        fee,
        amount,
        context
    );
    // INV-FEE-1 (checked last — most likely to fail, and we want the others first)
    assert_eq!(
        fee + net,
        amount,
        "INV-FEE-1 VIOLATED: fee({}) + net({}) = {} != amount({}) — context: {}",
        fee,
        net,
        fee + net,
        amount,
        context
    );
}

// ── Op definitions ─────────────────────────────────────────────────────────────

/// Operations the fee harness drives.
#[derive(Arbitrary, Debug)]
enum FeeOp {
    /// Set the flat fee rate and assert invariants on a direct arithmetic check.
    SetFlatFee {
        fee_bps: u32,
        /// Tag for gen::small_u32 skew.
        ftag: u8,
        /// Amount to compute fee on (not a real fund_invoice call — direct arithmetic).
        amount: i128,
        atag: u8,
        /// Token decimals selector (7 or 0 for stress test).
        decimals: u8,
    },

    /// Set a tier-specific fee override and assert invariants.
    SetTierFee {
        tier: u8,
        fee_bps: u32,
        ftag: u8,
        amount: i128,
        atag: u8,
    },

    /// Assert that fee+net==amount across the entire tier table simultaneously
    /// for a given amount — verifies no tier combination produces a leak.
    AssertAllTiers {
        amount: i128,
        atag: u8,
        base_fee_bps: u32,
        btag: u8,
    },

    /// Boundary: amount == 0 must produce fee=0 and net=0 (or be rejected).
    ZeroAmount,

    /// Boundary: amount == 1 stroop (minimum valid).
    MinAmount { fee_bps: u32, ftag: u8 },

    /// Boundary: amount at MAX_AMOUNT.
    MaxAmount { fee_bps: u32, ftag: u8 },

    /// Boundary: amount at MAX_AMOUNT + 1 (must be rejected, not panic).
    OverMax { fee_bps: u32, ftag: u8 },

    /// Tier boundary: amounts that are exactly on tier breakpoints.
    /// The tier table (investor_volume → tier) must resolve deterministically.
    TierBreakpoint {
        /// Volume in multiples of 1_000_000_000 (1 000 USDC).
        volume_k: u32,
        fee_bps: u32,
        ftag: u8,
    },

    /// Stress: very large fee_bps (close to 10_000) with large amount.
    MaxFee {
        amount: i128,
        atag: u8,
    },

    /// Direct arithmetic oracle: verify our invariant formula independently
    /// of any contract call.
    ArithmeticOracle {
        amount: i128,
        atag: u8,
        fee_bps: u32,
        ftag: u8,
        decimals: u8,
    },
}

// ── Harness entry point ────────────────────────────────────────────────────────

pub fn run(data: &[u8]) {
    let p = Protocol::deploy();
    super::drive::<FeeOp, _>(data, |op| {
        match op {
            // ── Direct arithmetic invariant checks ────────────────────────
            // These do not call into the contract — they verify the fee formula
            // itself is mathematically correct across the fuzz input space.
            // If they panic, the formula implementation in `kora_shared` has a bug.

            FeeOp::SetFlatFee { fee_bps, ftag, amount, atag, decimals } => {
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                let amount = gen::amount(amount, atag);
                if amount <= 0 || amount > MAX_AMOUNT {
                    return; // expected rejection — no invariant to check
                }
                let token_decimals = if decimals % 2 == 0 { 7u32 } else { 0u32 };
                if let Some(fee) = bps_of_normalized(amount, fee_bps, token_decimals) {
                    if let Some(net) = amount.checked_sub(fee) {
                        assert_fee_invariants(
                            amount,
                            fee,
                            net,
                            &format!("SetFlatFee fee_bps={} amount={} decimals={}", fee_bps, amount, token_decimals),
                        );
                    }
                }
                // overflow from bps_of_normalized → None is acceptable (very large amounts)
            }

            FeeOp::SetTierFee { tier, fee_bps, ftag, amount, atag } => {
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                let amount = gen::amount(amount, atag);
                if amount <= 0 || amount > MAX_AMOUNT {
                    return;
                }
                let _tier = gen::risk_tier(tier); // just ensure the tier enum is valid
                if let Some(fee) = bps_of_normalized(amount, fee_bps, 7) {
                    if let Some(net) = amount.checked_sub(fee) {
                        assert_fee_invariants(
                            amount,
                            fee,
                            net,
                            &format!("SetTierFee tier={} fee_bps={} amount={}", tier % 5, fee_bps, amount),
                        );
                    }
                }
            }

            FeeOp::AssertAllTiers { amount, atag, base_fee_bps, btag } => {
                let amount = gen::amount(amount, atag);
                if amount <= 0 || amount > MAX_AMOUNT {
                    return;
                }
                let base_bps = gen::small_u32(base_fee_bps, btag).min(10_000);

                for ordinal in 0u32..5 {
                    // Simulate a tier override: ordinal × 100 bps above base.
                    let tier_bps = (base_bps + ordinal * 50).min(10_000);
                    if let Some(fee) = bps_of_normalized(amount, tier_bps, 7) {
                        if let Some(net) = amount.checked_sub(fee) {
                            assert_fee_invariants(
                                amount,
                                fee,
                                net,
                                &format!("AssertAllTiers ordinal={} tier_bps={} amount={}", ordinal, tier_bps, amount),
                            );
                            // INV-FEE-5: per-tier fee must lie within [0, 10_000] bps.
                            assert!(
                                tier_bps <= 10_000,
                                "INV-FEE-5 VIOLATED: tier_bps {} > 10_000",
                                tier_bps
                            );
                        }
                    }
                }
            }

            FeeOp::ZeroAmount => {
                // INV-FEE-6: amount=0 → fee=0 and net=0 (arithmetic is defined)
                // or bps_of_normalized returns None (also fine — just must not panic).
                let fee = bps_of_normalized(0, 50, 7).unwrap_or(0);
                let net = 0i128.checked_sub(fee).unwrap_or(0);
                // No invariant violation for amount=0 specifically, but must not panic.
                let _ = (fee, net);
            }

            FeeOp::MinAmount { fee_bps, ftag } => {
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                let amount = 1i128; // 1 stroop — minimum valid
                if let Some(fee) = bps_of_normalized(amount, fee_bps, 7) {
                    if let Some(net) = amount.checked_sub(fee) {
                        assert_fee_invariants(
                            amount,
                            fee,
                            net,
                            &format!("MinAmount fee_bps={}", fee_bps),
                        );
                    }
                }
            }

            FeeOp::MaxAmount { fee_bps, ftag } => {
                // INV-FEE-7: MAX_AMOUNT must not panic.
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                let amount = MAX_AMOUNT;
                if let Some(fee) = bps_of_normalized(amount, fee_bps, 7) {
                    if let Some(net) = amount.checked_sub(fee) {
                        assert_fee_invariants(
                            amount,
                            fee,
                            net,
                            &format!("MaxAmount fee_bps={}", fee_bps),
                        );
                    }
                }
                // None from overflow → acceptable (MAX_AMOUNT × 10_000 overflows i128)
            }

            FeeOp::OverMax { fee_bps, ftag } => {
                // INV-FEE-7: MAX_AMOUNT + 1 must not panic (overflow → None is fine).
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                let amount = MAX_AMOUNT + 1; // out-of-range — contract should reject
                // Just verify no panic in the arithmetic layer.
                let _ = bps_of_normalized(amount, fee_bps, 7);
            }

            FeeOp::TierBreakpoint { volume_k, fee_bps, ftag } => {
                // Tier breakpoints from the marketplace tier table.
                // Exact breakpoints stress the boundary where tier resolution
                // flips — the fee invariants must hold at every breakpoint.
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                // Tier breakpoints in investor_volume (USDC, 7 decimals):
                // AAA: >= 1_000_000_000_000  (1M USDC)
                // AA:  >= 100_000_000_000    (100K USDC)
                // A:   >= 10_000_000_000     (10K USDC)
                // B:   >= 1_000_000_000      (1K USDC)
                // C:   < 1_000_000_000       (< 1K USDC)
                let breakpoints: [i128; 6] = [
                    1,
                    999_999_999,              // just under B threshold
                    1_000_000_000,            // exact B threshold
                    9_999_999_999,            // just under A threshold
                    10_000_000_000,           // exact A threshold
                    1_000_000_000_000,        // exact AAA threshold
                ];
                let amount = breakpoints[(volume_k as usize) % breakpoints.len()];
                if amount <= 0 { return; }
                if let Some(fee) = bps_of_normalized(amount, fee_bps, 7) {
                    if let Some(net) = amount.checked_sub(fee) {
                        assert_fee_invariants(
                            amount,
                            fee,
                            net,
                            &format!("TierBreakpoint amount={} fee_bps={}", amount, fee_bps),
                        );
                    }
                }
            }

            FeeOp::MaxFee { amount, atag } => {
                // Stress: 100% fee (10_000 bps) — net must be 0, fee == amount.
                let amount = gen::amount(amount, atag);
                if amount <= 0 || amount > MAX_AMOUNT {
                    return;
                }
                let fee_bps = 10_000u32;
                if let Some(fee) = bps_of_normalized(amount, fee_bps, 7) {
                    if let Some(net) = amount.checked_sub(fee) {
                        assert_fee_invariants(
                            amount,
                            fee,
                            net,
                            &format!("MaxFee amount={}", amount),
                        );
                        // With 100% fee, net may be 0 (if amount is exact multiple
                        // of scale) or a small positive residual from normalisation.
                        assert!(net >= 0, "MaxFee: net {} < 0", net);
                        // fee must equal amount or be less by at most scale-1 (normalisation).
                        let scale = 10i128.pow(7);
                        assert!(
                            fee >= amount - (scale - 1),
                            "MaxFee: fee {} << amount {} (gap > scale-1={})",
                            fee, amount, scale - 1
                        );
                    }
                }
            }

            FeeOp::ArithmeticOracle { amount, atag, fee_bps, ftag, decimals } => {
                // Fully independent oracle: re-derive fee and net from scratch
                // using a different (simplified) formula and compare.
                let amount = gen::amount(amount, atag);
                let fee_bps = gen::small_u32(fee_bps, ftag).min(10_000);
                let token_decimals = (decimals as u32) % 8; // 0..7
                if amount <= 0 || amount > MAX_AMOUNT { return; }

                // Oracle formula: truncate at full precision, no scale normalisation.
                let oracle_fee = amount
                    .checked_mul(fee_bps as i128)
                    .and_then(|v| v.checked_div(10_000));

                if let Some(oracle_fee) = oracle_fee {
                    if let Some(oracle_net) = amount.checked_sub(oracle_fee) {
                        // Oracle invariants (no normalisation rounding here).
                        assert!(oracle_fee >= 0, "ArithmeticOracle: fee {} < 0", oracle_fee);
                        assert!(oracle_net >= 0, "ArithmeticOracle: net {} < 0", oracle_net);
                        assert_eq!(
                            oracle_fee + oracle_net,
                            amount,
                            "ArithmeticOracle INV-FEE-1: fee+net != amount at fee_bps={} amount={}",
                            fee_bps, amount
                        );
                    }
                }

                // Now compare with the normalised formula — the only allowed
                // difference is that normalisation may move up to (scale-1) stroops
                // from fee to net (rounding down the fee to a multiple of scale).
                let normalised_fee = bps_of_normalized(amount, fee_bps, token_decimals);
                if let (Some(oracle_fee), Some(norm_fee)) = (oracle_fee.filter(|_| token_decimals > 0), normalised_fee) {
                    let scale = 10i128.pow(token_decimals);
                    let diff = oracle_fee - norm_fee; // always >= 0 (normalisation rounds down)
                    assert!(
                        diff >= 0 && diff < scale,
                        "ArithmeticOracle: normalised_fee={} differs from oracle_fee={} by {} >= scale={} (decimals={})",
                        norm_fee, oracle_fee, diff, scale, token_decimals
                    );
                }
            }
        }
    });
}

// ── Smoke test corpus seeds for CI ────────────────────────────────────────────
//
// These are deterministic, hand-crafted inputs that exercise the most
// important boundary conditions.  They run as part of the regular
// smoke harness via `tests/smoke.rs` (see `fuzz_marketplace_fee` entry).
//
// The seed functions are unconditionally `pub` so `smoke.rs` can call them
// directly from the non-ignored CI tests without needing `--ignored`.

/// Run INV-FEE-1..7 assertions on a representative set of (amount, fee_bps, decimals).
/// Call this from any test or smoke harness — it does not require `#[test]`.
pub fn assert_fee_seeds_representative() {
    let cases: &[(i128, u32, u32)] = &[
        // (amount, fee_bps, token_decimals)
        (10_000_000_000, 50, 7),         // 10K USDC, 0.5% fee
        (10_000_000_000, 500, 7),        // 10K USDC, 5% fee
        (10_000_000_000, 10_000, 7),     // 10K USDC, 100% fee
        (1, 50, 7),                      // 1 stroop, 0.5% fee → fee=0, net=1
        (1, 10_000, 7),                  // 1 stroop, 100% fee
        (MAX_AMOUNT, 50, 7),             // MAX_AMOUNT (may overflow)
        (10_000_000_007, 3333, 7),       // prime-ish, 33.33% fee
        (1_000_000_000, 50, 7),          // exact B threshold
        (999_999_999, 50, 7),            // just below B threshold
        (10_000_000_000, 50, 0),         // no decimal normalisation
    ];
    for &(amount, fee_bps, decimals) in cases {
        if let Some(fee) = bps_of_normalized(amount, fee_bps, decimals) {
            if let Some(net) = amount.checked_sub(fee) {
                assert_fee_invariants(
                    amount,
                    fee,
                    net,
                    &format!("seed: amount={} fee_bps={} decimals={}", amount, fee_bps, decimals),
                );
            }
        }
    }
}

/// Run INV-FEE-1 assertions on tier breakpoint boundary values.
/// Call this from any test or smoke harness — it does not require `#[test]`.
pub fn assert_fee_seeds_tier_breakpoints() {
    let breakpoints: &[(i128, u32)] = &[
        (999_999_999, 150),    // just under B → B tier fee
        (1_000_000_000, 150),  // exact B breakpoint
        (1_000_000_001, 100),  // just over B → A tier fee
        (9_999_999_999, 100),  // just under A
        (10_000_000_000, 75),  // exact A breakpoint
        (10_000_000_001, 75),  // just over A
    ];
    for &(amount, fee_bps) in breakpoints {
        if let Some(fee) = bps_of_normalized(amount, fee_bps, 7) {
            if let Some(net) = amount.checked_sub(fee) {
                assert_fee_invariants(
                    amount,
                    fee,
                    net,
                    &format!("tier_breakpoint: amount={} fee_bps={}", amount, fee_bps),
                );
            }
        }
    }
}

#[cfg(test)]
pub mod seeds {
    use super::*;

    /// Verify INV-FEE-1 holds for a representative set of (amount, fee_bps) pairs.
    #[test]
    pub fn fee_invariants_hold_for_representative_inputs() {
        super::assert_fee_seeds_representative();
    }

    /// Verify that the tier breakpoint boundary values never lose money.
    #[test]
    pub fn tier_breakpoints_no_rounding_loss() {
        super::assert_fee_seeds_tier_breakpoints();
    }
}
