#!/bin/bash
# packaging/deploy-indexer.sh
# Deployment automation script for community-run Kora indexer instances
#
# Usage: sudo ./packaging/deploy-indexer.sh [testnet|mainnet]

set -e

NETWORK="${1:-testnet}"
if [ "$NETWORK" != "testnet" ] && [ "$NETWORK" != "mainnet" ]; then
    echo "Usage: $0 [testnet|mainnet]"
    exit 1
fi

echo "════════════════════════════════════════════════════════"
echo " Kora Indexer Deployment Script"
echo " Network: $NETWORK"
echo "════════════════════════════════════════════════════════"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

# Install dependencies
echo "[1/8] Installing system dependencies..."
apt-get update -qq
apt-get install -y curl git build-essential sqlite3 jq

# Install Rust if not present
if ! command -v cargo &> /dev/null; then
    echo "[2/8] Installing Rust toolchain..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
else
    echo "[2/8] Rust already installed, skipping..."
fi

# Create kora user
echo "[3/8] Creating kora system user..."
if ! id -u kora &> /dev/null; then
    useradd --system --create-home --shell /bin/bash kora
else
    echo "    User 'kora' already exists, skipping..."
fi

# Clone or update repository
echo "[4/8] Setting up Kora repository..."
KORA_HOME="/opt/kora"
if [ ! -d "$KORA_HOME" ]; then
    mkdir -p /opt/kora
    cd /opt
    sudo -u kora git clone https://github.com/kora-finance/contracts.git kora
else
    echo "    Repository exists, pulling latest changes..."
    cd $KORA_HOME
    sudo -u kora git pull origin main
fi

cd $KORA_HOME

# Checkout stable release
echo "[5/8] Checking out latest stable release..."
LATEST_TAG=$(git describe --tags --abbrev=0)
sudo -u kora git checkout $LATEST_TAG
echo "    Using version: $LATEST_TAG"

# Build indexer
echo "[6/8] Building indexer (this may take 5-10 minutes)..."
cd services/indexer
sudo -u kora cargo build --release

# Configure environment
echo "[7/8] Configuring environment for $NETWORK..."
if [ ! -f ".env" ]; then
    cat > .env <<EOF
# Auto-generated by deploy-indexer.sh on $(date)
STELLAR_NETWORK=$NETWORK
SOROBAN_RPC_URL=http://localhost:8000/soroban/rpc
DATABASE_URL=sqlite:///opt/kora/services/indexer/indexer.db
START_LEDGER=0
CHECKPOINT_INTERVAL_SECONDS=60
POLL_INTERVAL_MS=1000
RUST_LOG=info

# Contract addresses (update these from deployments/${NETWORK}/addresses.json)
CONTRACT_INVOICE_NFT=
CONTRACT_MARKETPLACE=
CONTRACT_FINANCING_POOL=
CONTRACT_RISK_REGISTRY=
CONTRACT_PRICE_ORACLE=
CONTRACT_GOVERNANCE=
CONTRACT_ACCESS_CONTROL=
EOF
    chown kora:kora .env
    echo "    ⚠️  Created .env file - EDIT CONTRACT ADDRESSES before starting service!"
    echo "    File location: /opt/kora/services/indexer/.env"
else
    echo "    .env file already exists, skipping..."
fi

# Create log directory
mkdir -p /var/log/kora
chown kora:kora /var/log/kora

# Install systemd service
echo "[8/8] Installing systemd service..."
cp $KORA_HOME/packaging/kora-indexer.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable kora-indexer

echo ""
echo "════════════════════════════════════════════════════════"
echo " ✅ Deployment Complete!"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Edit contract addresses in /opt/kora/services/indexer/.env"
echo "  2. Ensure Soroban RPC node is running at http://localhost:8000"
echo "  3. Start the indexer: sudo systemctl start kora-indexer"
echo "  4. Check status: sudo systemctl status kora-indexer"
echo "  5. View logs: sudo journalctl -u kora-indexer -f"
echo ""
echo "For verification:"
echo "  cd /opt/kora && ./tools/verify-indexer.sh"
echo ""
echo "Documentation: docs/RUNNING_A_NODE.md"
